### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by claudeisakeeb** [ctc-uci/cell-dogs-frontend#8]
## Overview
"The best programmers don't write code, they copy it" - Senior SWE Sai Vipin Siripurapu, August 2022

TODO: LINK FIGMA

- Set up a basic donation form skeleton using Chakra UI components
  - Refer to Chakra Documentation for syntax
  - Follow the Database Model for adding new fields
- Add validation using Yup
  - Refer to [FYA Yup Example](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/components/Login/LoginForm.jsx) as an example of what to do
  - Refer to Yup Documentation for syntax

## Notes
- Refer to bootcamp task 2 and Chakra documentation for how to implement input fields.
- Refer to Yup and react-hook-form documentation for how to implement validation.
- General page positioning should be done with flexbox
- The end product should look exactly like the Figma.

## Acceptance Criteria
For aesthetics
- End product looks exactly like Figma

For validation
- Both input fields are strings and required (Reference[ FYA Yup](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/components/Login/LoginForm.jsx))
- In case you're wondering, Firebase will be handling the **actual** validation, but that part comes later :)
- This task should be demod to tech leads

## Resources
- [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
- [Chakra Input Documentation](https://chakra-ui.com/docs/components/input)
- [FYA Yup](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/components/Login/LoginForm.jsx)
- [Yup Documentation](https://www.npmjs.com/package/yup)
- [Yup Youtube video](https://www.youtube.com/watch?v=RQ1E2EjyqY4)
- [React Hook Form Documentation](https://react-hook-form.com/)
- Screenshot of the Login page (The Figma isn't shared at the time I'm making this :P)
![image](https://user-images.githubusercontent.com/47193525/200968402-98158fc5-6f28-41b9-9b8c-fe8ba03c322e.png)

### As always, feel free to pm Claude or Alan on Slack for support

**Comment by alanchangxyz** [comment]
Note: This task is likely going to spill into winter quarter so do this after #10
